### ISSUE TITLE
Prevent entry Frequency=0 in ini-file

### ISSUE THREAD

**Issue by andimik** [KejPi/AbracaDABra#28] opened 2022-07-27 18:43 UTC
During listening to this radio station it suddenly came a 2nd entry for the complete mux (maybe due to reception problems) but without the Ensemble Label and no DAB channel information.

![grafik](https://user-images.githubusercontent.com/24510556/181347142-116c26f0-59cf-4b31-a334-20678d91269b.png)

And the `ini`-file [AbracaDABra.zip](https://github.com/KejPi/AbracaDABra/files/9202728/AbracaDABra.zip) got this invalid entry, which might cause this issue:

```
1\Ensemble\1\Frequency=0
1\Ensemble\1\Label=
1\Ensemble\1\ShortLabel=
```

So I would suggest the tool not to save such invalid frequencies.

**Comment by KejPi** [comment] 2022-07-29 16:28
This is probably caused by combination of two ensembles in the same channel. I would be interested to get a recording 😉 This is a consequence of implementing endsemble change (issue #8). For sure I can implement the proposed workaround but it will not help with the cause.

**Comment by andimik** [comment] 2022-07-29 16:54
I can't receive two different ensembles on one channel. I guess this was a reception problem.

**Comment by KejPi** [comment] 2022-07-29 17:15
OK, I will check that.

**Comment by andimik** [comment] 2022-07-30 06:29
> This is probably caused by combination of two ensembles in the same channel.

No, otherwise frequency would not be 0.

**Comment by KejPi** [comment] 2022-08-03 11:32
It should be fixed now, closing.

**Closed by KejPi** 2022-08-03 11:32 UTC
